### ISSUE TITLE
Create dependabot file

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#461]
**Beginner friendly**

Create a [dependabot](https://dependabot.com/) file so npm deps get PR'd automatically.

Example file, I'll leave it as an exercise to the reader to work out where it should live: 

```
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
  - dependency-type: production
  commit-message:
    prefix: "[DEPS]"
```
